### ISSUE TITLE
Reduce divisions between hours ?

### ISSUE THREAD

**Issue by anubhav-sl** [karolkozer/planby#2]
Any option to reduce divisions between hours in timeline .

**Comment by karolkozer** [comment]
Hi,
Thank you for your message.
Do you want to change the width of a hour?

**Comment by anubhav-sl** [comment]
Yes, the width between the hours.
Thanks

**Comment by karolkozer** [comment]
This feature is almost finished. I am going to release this feature this week. 
You will be able to set width of the whole day -> dayWidth in useEpg.
The measure of the hours will be calculated automatically because it depends on the "DAY_WIDTH" value eg.
24h * 300px(your custom hour width) = 7200px -> dayWidth.

**Comment by karolkozer** [comment]
@anubhav-sl New version 0.1.32 with dayWidth prop has been released.
