### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by lambrosx77** [karolkozer/planby#59]
Hi,

Thank you for sharing your nice project.

Licence is MIT on NPM, not on GitHub so I'm not sure if we can use Planby on our non commercial industrial project?

Thank you for the answer.

**Comment by karolkozer** [comment]
Hi,

You can use Planby in your commercial and personal project.
Here is the license: https://github.com/karolkozer/planby/blob/master/LICENSE

I will fix this issue on NPM.

**Comment by marcortw** [comment]
Sorry for heating up an old thread, but @karolkozer I wonder if that statement stilll holds true since [the commit](https://github.com/karolkozer/planby/commit/dba8319d4cc86dc70da5686ae617619606233cd8) you switched from MIT to custom? That change was before this thread, though. So overall, I'm a bit confused by the wording in your custom license.

I would like to give planby a try in my side-project which might end up to be commercial and tbh I'm not sure if your current license allows that.

**Comment by karolkozer** [comment]
@marcortw you can use in your project.
