### ISSUE TITLE
Dynamic height render is broken

### ISSUE THREAD

**Issue by david303** [karolkozer/planby#8]
Hi and thanks for this library!

I'm working on an implementation and seems that without a concrete fixed pixel height the channels/programs do not render properly.

Replicated by forking your codepen and just changing Epg container height to "auto":
<img width="510" alt="obraz" src="https://user-images.githubusercontent.com/8525763/172159068-291c1cce-b97a-4887-a898-47333eed0ae4.png">
https://codesandbox.io/s/planby-epg-demo-forked-001b8r?file=/src/App.js

Only the first channel is rendered, the rest of the channels are missing, space seems to be calculated correctly for them but it's all empty.
![obraz](https://user-images.githubusercontent.com/8525763/172159812-cfa482ff-2dd1-42a3-a319-e73566aa1416.png)

Interestingly, if I modify the code to force a hot reload it renders correctly, so seems like something related to the initial render.

**Comment by karolkozer** [comment]
Hi @david303 , 

Thank you very much for your message and interested in Planby component.

I would suggest giving a specific value always for the component container.

It may be related to the lack of the initial value of the container height when you set the value "height: auto" and the application height during the calculation is very small.


**"Interestingly, if I modify the code to force a hot reload it renders correctly, so seems like something related to the initial render."**
When reloading, the height of the window / container is already given, so then it works properly with property"height: auto".


I will check if it can be improved if you give an "height: auto" value of the container height to render all the channels at the initial render stage.

**Comment by 239144498** [comment]
I also encountered the same problem as you, after my careful investigation, I added in the App.js file
`console.log(isLoading,  {...getLayoutProps()});`
It is found that each time the result returned, the first few times must be empty
`
Object { programs: [], channels: [], startDate: "2022-05-25T00:00:00"  

Object { programs: [], channels: [], startDate: "2022-05-25T00:00:00"  

Object { programs: (1440) […], channels: [], startDate: "2022-05-25T00:00:00",  

Object { programs: (1440) […], channels: (52) […], startDate: "2022-05-25T00:00:00",  
`

I found that it may be due to the first load
`const {isLoading, getEpgProps, getLayoutProps} = useApp();`
Because the obtained data is loaded too slowly, it renders when empty data is obtained, so incorrect rendering results are obtained. Although the data can be obtained several times later, the rendering parameters of the first empty data are used, so Dynamic height render appears. is broken

Hope this clue will be useful to fix the bug
