### ISSUE TITLE
Plans to support Vue JS?

### ISSUE THREAD

**Issue by saenzramiro** [karolkozer/planby#9]
I'm a Vue JS developer and it will be great for me to integrate this amazing library to my project.

**Comment by karolkozer** [comment]
Hi @saenzramiro ,

Thank you very much for your message and interested in Planby component 😊. 
How did you find this component 😊?

Now, I do not have any plans to rewrite this component to Vue. 


Please see this article how to use React components into vue, maybe it could help 
- "Using React components directly in Vue components" -  https://cedricmckinnie.medium.com/using-react-components-directly-in-vue-components-with-or-without-typescript-part-2-full-ccf7225b4304

- vuera package - use React components in your Vue app- https://github.com/akxcv/vuera
- babel-plugin-transform-react-to-vue -https://github.com/vueact/babel-plugin-transform-react-to-vue

@saenzramiro If you find some another ideas how to integrate / convert this component from React to Vue, please let me know.

I will be looking for some solutions.

**Comment by saenzramiro** [comment]
Thank you for your answer.

I did not use it yet because is for React, but I will follow those links to try to integrate in my project. Thanks again.

**Comment by sondh0127** [comment]
I have made a Planby Vue version here. Vue 3 is currently supported. I hope you find it useful.
[https://github.com/sondh0127/vue-epg-planby](https://github.com/sondh0127/vue-epg-planby)

**Comment by saenzramiro** [comment]
Great job @sondh0127! I will take a look.

Maybe @karolkozer can makes official the Vue JS version by creating a new repo. 😉😉

**Comment by karolkozer** [comment]
Hey @sondh0127 

Great job! This component looks really nice! 😁 🚀

In the time range the full clock hour is only valid. Please disable the minute options because it causes some problems in the EPG. Docs: https://github.com/karolkozer/planby#useepg
Please find attached screenshot
 
![Screenshot 2022-07-22 at 19 05 21](https://user-images.githubusercontent.com/29305289/180489600-e1ef5b57-16f9-4971-b249-81dbe215d29f.png)

There is some problems with EPG on Opera
<img width="1365" alt="Screenshot 2022-07-22 at 19 11 47" src="https://user-images.githubusercontent.com/29305289/180490746-5dcb9424-9bef-4c74-933f-6caf32b4eeb0.png">

@sondh0127 maybe its better to use CodeSandbox than Stackblitz

@saenzramiro @sondh0127  maybe we can think about official Planby Vue.js 🚀
